version: 2

builds:
  - id: default
    binary: ghat
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
  - id: darwin
    binary: ghat
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

signs:
  - cmd: rcodesign
    args:
      - sign
      - "${artifact}"
    ids:
      - darwin
    artifacts: binary
    output: false

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

homebrew_casks:
  - repository:
      owner: rlespinasse
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/rlespinasse/github-actions-toolbox
    description: CLI toolbox for GitHub Actions
    binaries:
      - ghat
